version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/usr/src/app/backend
      - ./backend/source_documents:/usr/src/app/source_documents
      - ./backend/chroma_db:/usr/src/app/backend/chroma_db
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - web

networks:
  default:
    driver: bridge
